all:
  hosts:
    hfal12k8n1:
      ansible_host: 167.235.100.67
      ip: 10.10.10.1
      ip6: fd40:89ce:20d:e768::1
      access_ip: 10.10.10.1
    hfal12k8n2:
      ansible_host: 167.235.100.68
      ip: 10.10.10.2
      ip6: fd40:89ce:20d:e768::2
      access_ip: 10.10.10.2
    hfal12k8n3:
      ansible_host: 167.235.100.66
      ip: 10.10.10.3
      ip6: fd40:89ce:20d:e768::3
      access_ip: 10.10.10.3
    hfal12k8n4:
      ansible_host: 167.235.100.122
      ip: 10.10.10.4
      ip6: fd40:89ce:20d:e768::4
      access_ip: 10.10.10.4
    hfal12k8n5:
      ansible_host: 167.235.100.121
      ip: 10.10.10.5
      ip6: fd40:89ce:20d:e768::5
      access_ip: 10.10.10.5
  children:
    kube_control_plane:
      hosts:
        hfal12k8n1:
        hfal12k8n2:
    kube_node:
      hosts:
        hfal12k8n1:
        hfal12k8n2:
        hfal12k8n3:
        hfal12k8n4:
        hfal12k8n5:
    etcd:
      hosts:
        hfal12k8n1:
        hfal12k8n2:
        hfal12k8n3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
